# Generated by Django 2.1.2 on 2018-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='impdates',
            fields=[
                ('id', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('dob', models.IntegerField(default=20)),
                ('doj', models.IntegerField(default=20)),
                ('bt', models.IntegerField(default=20)),
            ],
        ),
    ]
