# Generated by Django 2.1.2 on 2018-10-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181010_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_id',
            new_name='id',
        ),
    ]
