# Generated by Django 2.1 on 2018-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=123)),
                ('Fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Duration', models.IntegerField(default=2)),
            ],
        ),
    ]
