# Generated by Django 2.1 on 2018-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harishApp', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=123)),
                ('Contact', models.IntegerField(default=10)),
                ('Email', models.EmailField(max_length=90)),
                ('Password', models.CharField(max_length=60)),
            ],
        ),
    ]
