# Generated by Django 2.1 on 2018-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harishApp', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Id', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('HR_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField(default=10)),
                ('Purpose', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=342)),
                ('Status', models.CharField(max_length=34)),
            ],
        ),
    ]
